FROM redis/redisinsight:latest



ENV RI_APP_PORT=5540
ENV RI_APP_HOST=0.0.0.0
# ENV RI_SERVER_TLS_KEY 5540
# ENV RI_SERVER_TLS_CERT 5540
# ENV RI_ENCRYPTION_KEY 5540
# ENV RI_LOG_LEVEL verbose
# ENV RI_FILES_LOGGER true
# ENV RI_STDOUT_LOGGER true
# ENV RI_PROXY_PATH 5540